root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/gohtmx"
  cmd = "make build_tmp"
  delay = 500 # ms
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/gohtmx"
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "yaml", "tpl", "tmpl", "html", "properties", "ini", "conf", "toml", "yml"]
  kill_delay = 0 # ms
  log = "air_errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false