version: "3.9"

services:
  db:
    image: "postgres:${DB_VERSION}-alpine"
    container_name: gohtmx-db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - gohtmx
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_POST: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      timeout: 45s
      interval: 10s
      retries: 5

  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: gohtmx-api
  #   restart: always
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   networks:
  #     - gohtmx
  #   environment:
  #     DB_HOST: db
  #   depends_on:
  #     - db

  adminer:
    image: adminer
    container_name: gohtmx-adminer
    restart: always
    networks:
      - gohtmx
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  gohtmx:
