// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Completed bool               `json:"completed"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
	DeletedAt pgtype.Timestamptz `json:"deletedAt"`
}
