// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTodos(ctx context.Context) (int64, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id uuid.UUID) error
	FindAllTodos(ctx context.Context, arg FindAllTodosParams) ([]Todo, error)
	FindTodoById(ctx context.Context, id uuid.UUID) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
